#© 2021 Sean Murdock

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-stedi-landon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-stedi-landon
  template:
    metadata:
      labels:
        app: prod-stedi-landon
    spec:
      containers:
        - name: prod-stedi-landon
          image: gcr.io/cubs-consulting/stedi #NEEDS TO REFERNCE THE NEW UNCREATED ARTIFACT REPO
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets-landon
                  key: REDIS_PASS
            - name: REDIS_HOST
              value: "redis-secrets-landon"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
          ports:
            - containerPort: 443
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 3
            periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: prod-stedi-landon-nodeport
spec:
  selector:
    app: prod-stedi-landon
  type: NodePort
  ports:
    - port: 80
      targetPort: 4567
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landon-stedi-prod-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: prod-stedi-landon-public #NOT BEEN CREATED YET
    networking.gke.io/managed-certificates: prod-stedi-landon-certificate
    # kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-stedi-landon-nodeport #NEEDS TO MATCH LINE 53
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: prod-stedi-landon-certificate #NEEDS TO MATCH LINE 68
spec:
  domains:
    - landon.cit262.com # this is a dns record and hasn't been made yet- we need to make it first
    
